# Generated by Django 2.2.1 on 2019-05-22 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_master.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default='Mobile', on_delete=django.db.models.deletion.CASCADE, to='product_master.SubCategory'),
        ),
    ]
